#!/usr/bin/env python
# coding=utf-8

import algo
import sys
import os
import mysocket

default_port = 10007

def forkserver(func1, func2, port):
    pid = os.fork()
    if pid == 0:
        func1(func2, port)
    else:
        pass

def socketfunc(indata):
    try:
        str = indata.decode("base64")
    except Exception:
        return ""
    if str != "":
        output = ""
        for k,h,v in algo.parse(str):
            output += "%s\t%s\t%s\n" % (k,v,h.replace(" ", "_"))
        return output.encode("base64")
    else:
        return ""

def main():
    try:
        import psyco
        psyco.full()
    except ImportError:
        pass

    algo.parse("__setmode=abc")
    if len(sys.argv) > 1 and sys.argv[1] == "-b":
        mysocket.setverbose(False)
        forkserver(mysocket.tcpserver, socketfunc, default_port)
    else:
        mysocket.setverbose(True)
        mysocket.tcpserver(socketfunc, default_port)

if __name__ == "__main__":
    main()

