#!/usr/bin/env python
# coding=utf-8

import sys
import mysocket

def parsefunc(keyb, host="localhost"):
    src = keyb.encode("base64")
    ret = mysocket.tcpsend(src, host, 10007)
    if type(ret).__name__ == "str":
        try:
            return ret.decode("base64")
        except Exception:
            return ""
    else:
        return ""

def main():
    argc = len(sys.argv)
    if argc == 1:
        pass
    elif argc == 2:
        sys.stdout.write(parsefunc(sys.argv[1]))
    elif argc == 3:
        sys.stdout.write(parsefunc(sys.argv[2], sys.argv[1]))
    else:
        pass

if __name__ == "__main__":
    main()
